//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 02:05:35 PM EDT 
//


package org.eclipse.tracecompass.tmf.xmlconverter.core.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Define a change of state in the state system being built.
 * 
 * <p>Java class for stateChange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stateChange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="stateAttribute" type="{}stateAttribute" maxOccurs="unbounded"/>
 *           &lt;element name="stateValue" type="{}stateValue"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="if" type="{}conditionSingle"/>
 *           &lt;element name="then" type="{}stateChange"/>
 *           &lt;element name="else" type="{}stateChange" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stateChange", propOrder = {
    "stateAttribute",
    "stateValue",
    "_if",
    "then",
    "_else"
})
public class StateChange {

    protected List<StateAttribute> stateAttribute;
    protected StateValue stateValue;
    @XmlElement(name = "if")
    protected ConditionSingle _if;
    protected StateChange then;
    @XmlElement(name = "else")
    protected StateChange _else;

    /**
     * Gets the value of the stateAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StateAttribute }
     * 
     * 
     */
    public List<StateAttribute> getStateAttribute() {
        if (stateAttribute == null) {
            stateAttribute = new ArrayList<StateAttribute>();
        }
        return this.stateAttribute;
    }

    /**
     * Gets the value of the stateValue property.
     * 
     * @return
     *     possible object is
     *     {@link StateValue }
     *     
     */
    public StateValue getStateValue() {
        return stateValue;
    }

    /**
     * Sets the value of the stateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateValue }
     *     
     */
    public void setStateValue(StateValue value) {
        this.stateValue = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionSingle }
     *     
     */
    public ConditionSingle getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionSingle }
     *     
     */
    public void setIf(ConditionSingle value) {
        this._if = value;
    }

    /**
     * Gets the value of the then property.
     * 
     * @return
     *     possible object is
     *     {@link StateChange }
     *     
     */
    public StateChange getThen() {
        return then;
    }

    /**
     * Sets the value of the then property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateChange }
     *     
     */
    public void setThen(StateChange value) {
        this.then = value;
    }

    /**
     * Gets the value of the else property.
     * 
     * @return
     *     possible object is
     *     {@link StateChange }
     *     
     */
    public StateChange getElse() {
        return _else;
    }

    /**
     * Sets the value of the else property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateChange }
     *     
     */
    public void setElse(StateChange value) {
        this._else = value;
    }

}
