//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 02:05:35 PM EDT 
//


package org.eclipse.tracecompass.tmf.xmlconverter.core.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tmfxml complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tmfxml">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="timeGraphView" type="{}timeGraphView" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stateProvider" type="{}stateProvider" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tmfxml", propOrder = {
    "timeGraphViewOrStateProvider"
})
public class Tmfxml {

    @XmlElements({
        @XmlElement(name = "timeGraphView", type = TimeGraphView.class),
        @XmlElement(name = "stateProvider", type = StateProvider.class)
    })
    protected List<Object> timeGraphViewOrStateProvider;

    /**
     * Gets the value of the timeGraphViewOrStateProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeGraphViewOrStateProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeGraphViewOrStateProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeGraphView }
     * {@link StateProvider }
     * 
     * 
     */
    public List<Object> getTimeGraphViewOrStateProvider() {
        if (timeGraphViewOrStateProvider == null) {
            timeGraphViewOrStateProvider = new ArrayList<Object>();
        }
        return this.timeGraphViewOrStateProvider;
    }

}
