//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.03 at 12:33:25 PM EST 
//


package org.eclipse.tracecompass.tmf.attributetree.core.xmlmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.eclipse.tracecompass.tmf.attributetree.core.xmlModel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AttributeTreeRoot_QNAME = new QName("", "attributeTreeRoot");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.eclipse.tracecompass.tmf.attributetree.core.xmlModel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttributeTreeRoot }
     * 
     */
    public AttributeTreeRoot createAttributeTreeRoot() {
        return new AttributeTreeRoot();
    }

    /**
     * Create an instance of {@link AttributeNode }
     * 
     */
    public AttributeNode createAttributeNode() {
        return new AttributeNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeTreeRoot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attributeTreeRoot")
    public JAXBElement<AttributeTreeRoot> createAttributeTreeRoot(AttributeTreeRoot value) {
        return new JAXBElement<AttributeTreeRoot>(_AttributeTreeRoot_QNAME, AttributeTreeRoot.class, null, value);
    }

}
